WebThingsIO/zigbee-adapter

zb-classifier.js, zb-property.js
Also, fix issue when trying to set a read-only property.
=> Report smartPlug properly.

.gitignore, package.json, yarn.lock
=> Bundle dependencies.

zb-at.js
Fixing the description for SL command
=> Fixes AT command description typo

package.sh
This is a copy of the zwave-adapter's package.sh
=> Updated package.sh to be compatible with addon-builder

package.json, yarn.lock, zb-adapter.js, zb-classifier.js, zb-node.js, zb-property.js, zb-zdo.js
Add defaultRsp
Add support for extended timeout
Add support for temperature sensor
Add support for occupancy sensor
=> Add support for Motion sensor

package.json, yarn.lock, zb-adapter.js, zb-node.js, zb-zdo.js
This doesn't actually support OTA updates as we
always so that there are no updates available, but
some devices seem to respond better when we indicate
that we support OTA.
This PR also includes some cleanup of the ZDO sequence number generation.
=> Add support for the genOta cluster

package.json, yarn.lock, zb-adapter.js, zb-classifier.js, zb-node.js, zb-property.js
Sorry - a bit large. I'm going to continue to do testing, but I wanted to check this in since it seems to be working.
=> Save config

zb-adapter.js, zb-classifier.js, zb-families.js, zb-family.js, zb-node.js, zb-property.js, zb-xiaomi.js
In particular, the following modelIds:
lumi.plug
lumi.sensor_magnet
lumi.sensor_switch
lumi.sensor_motion
I've noticed that the xiaomi sensors seem to disappear after
a few hours. There is some extended detail here:
https://community.hubitat.com/t/xiaomi-devices-are-they-pairing-staying-connected-for-you/623/214
Inparticular adding particular brands of plugs seem to make the
xiaomi sensors work better, but I havn't confirmed this.
=> Add support for Xiaomi devices

zb-adapter.js
Also addressed a couple minor issues discovered during testing.
=> Added better error reporting for packet parsing errors

package.json
=> Bumped version to 0.5.1

package.json, zb-adapter.js, zb-classifier.js, zb-node.js
The bug in makeFuncCommand turns out to be fairly serious.
=> Fix powercfg voltage

package.json, zb-adapter.js, zb-node.js
- The 16-bit address may have changed since the configuration file was
saved. Update it in more places.
=> Update addr16 in more places

zb-adapter.js, zb-classifier.js, zb-node.js, zb-property.js, zb-xiaomi.js, zb-zdo.js
* fixes issues discovered with Cree bulbs
* adds support for Samsung SmartThings smartplugs
* improves a bunch of things around config reporting
=> A bunch of improvements

package.json
=> Bumped version to 0.5.5

package.json, zb-adapter.js, zb-node.js
Plus some other improvements for battery powered devices.
=> Fix develco regressions

zb-node.js
I rewrote this code as part of the last PR (not released yet) and I discovered this in testing.
=> Fix to rewritten code to retrieve initial value

package.json, zb-classifier.js, zb-node.js, zb-property.js
This allows IKEA color bulbs to be controlled.
=> Support XY colorspace

package.json, zb-adapter.js, zb-classifier.js, zb-constants.js, zb-node.js, zb-property.js
This also wound up revamping poll control, since
it was previously only activated for security
devices and the door lock isn't a security device.
=> Add support for door locks

package.json, zb-classifier.js, zb-debug.js, zb-node.js
=> Add support for Hue Dimmer Switch

zb-constants.js, zb-xiaomi.js
This was developed very slowly (whenever I had time during the weekends) and independently from #58 (I only saw that this was opened last month).
This seems to work even though
* I might be missing something obvious, in which case please point me to it
* at some cases the sensor updates stop getting received (I guess I might be missing something in the pairing process)
Will probably continue researching the later point during the holidays.
=> xiaomi-lumi.sensor_ht

zb-constants.js, zb-xiaomi.js
In particular, the WSDCGQ11LM which reports temperature,
relative humidity and barometric pressure.
=> Add support for Xiaomi Weather sensor

deconz-driver.js, zb-classifier.js, zb-xiaomi.js
=> Add TemperatureProperty and LeakProperty capabilities.

zb-adapter.js, zb-classifier.js, zb-constants.js
=> Improve classifier to properly detect ZLL bulbs

package.json, yarn.lock
Removed serial port dependency since zigbee no longer uses
the serial port directly.
=> Updated dependencies to latest version of serial prober

package.json, yarn.lock, zb-classifier.js, zb-constants.js, zb-node.js
The IKEA remotes and motion sensors will only work properly
with the ConBee dongle and not the Digi dongle.
=> Added support for the IKEA remote and motion sensor

package-lock.json, package.json, zb-constants.js
=> Add more ZHA device IDs

package-lock.json, package.json, zb-node.js
This was caused when the cmdQueue got moved from the adapter
to the driver.
=> Fixes #151

zb-classifier.js, zb-xiaomi.js
type is no longer used and will be going away soon.
=> Remove usage of thing type constants.

zb-classifier.js
=> Fix classification of Sengled LEDs.

manifest.json, package-lock.json, package.json, zb-classifier.js
=> Fix incorrect logic for min/max heat/cool targets.

manifest.json, package-lock.json, package.json, zb-classifier.js
=> Fix thermostat classification.

zb-classifier.js
=> Try to fix motion sensor classification.

manifest.json, package.json, zb-classifier.js
=> Fix detection of both lights and motion sensors.

zb-classifier.js
=> Fix button types.

zb-node.js
Currently, the adapter allows only one property per endpoint.
One of the Xiaomi Aqara Magic Cube endpoints contains multiple properties.
This PR adds support for multiple properties.
=> Allow multiple properties per endpoint

zb-adapter.js
discussion here https://github.com/WebThingsIO/zigbee-adapter/issues/224
=> small fix again

zb-classifier.js, zb-node.js
Good day,
This is based on this PR: https://github.com/WebThingsIO/zigbee-adapter/pull/124
In regards to this issue https://github.com/WebThingsIO/zigbee-adapter/issues/236 i made some changes to additionally support multiple endpoints on a single device. Also many thanks to @dhylands for doing the hard work.
Tested with my local Gateway setup and the [Innr RC 110](https://www.innr.com/de/produkt/remote-control/).
When setting the remote to scenes, the on/off button and +/- buttons work, however i did not manage to get the numbered buttons to work.
Setting the slider to lights enables the numbered buttons to alter the codes for the top 3 buttons. Each now controls a different property with each on/off and level state.
Anyways i'm very happy with the result.
I'm not very fluent with JS so …
=> Support even more multiple outlets 

zb-classifier.js, zb-node.js
The Scenes buttons and property on the TRADFRI remote control are functional again. While working through I found a number of cleanups. I sequenced these into a series of commits from most straightforward through to possibly intrusive.
Therefore I suggest that this is reviewed on a commit by commit basis, rather than looking at the PR as a whole.
=> Tradfri scene fixes and other cleanups.

index.js, manifest.json, package.json
need to add test in serialprober
https://github.com/WebThingsIO/serial-prober-node/pull/10
=> add option for raspbee serial

zb-adapter.js, zb-node.js
Two changes that reduce logging by this adapter
=> Suppress logging

README.md
=> Update README.md because of broken link.

pack-local.sh, zb-property.js, zb-xiaomi.js
This adds specific mappings for the Xiaomi Smartplug and Water sensor.
I included parts of the package script to quickly calculate and package small changes in JS files without building the whole project. On my local machine building the project took several minutes even for one changed line of code.
Tested this with my local setup. Even though the smartplug now has only its supported properties, the instantaneous power report seems a bit odd.
#247: The water sensor works now, however i had to re-pair it, until pressing the button made the LED flash quickly. At some point i tested the sensor with [deConz](https://phoscon.de/en/conbee2/software#deconz), which might made it work.
=> Support for Aqara Smartplug + Water Sensor

zb-classifier.js, zb-node.js
Hi there,
i implemented `moveToLevelWithOnOff` to handle commands sent from scene buttons on a Innr RC 110.
Additional events are registered to emit a "Scene X activated" event.
I tested this on my local gateway at home throughout the last 2 days.
@chas-iot Please test this again on your setup, to verify nothing breaks.
=> Add RC 110 Scene button support

manifest.json, package.json, zb-property.js
=> Fix minimum/maximum values.

index.js
Original code from @frederic34 in https://github.com/WebThingsIO/serial-prober-node/issues/11#issuecomment-736282755
@dhylands provided the idea to clone the probe in https://github.com/WebThingsIO/serial-prober-node/issues/11#issuecomment-736659917
=> Part 2 (of 2) of handling the latest deconz firmware

.github/workflows/build.yml, .github/workflows/release.yml, package-lock.json, src/driver/index.js, src/driver/xbee.js, src/index.js, src/zigbee2mqtt/zigbee2mqtt-device.ts, src/zigbee2mqtt/zigbee2mqtt-property.ts
Regenerate package-lock.json from Node.js 20
Preparing to release the Zigbee adapter add-on with Node.js 20 support.
=> Regenerate package-lock.json
