WebThingsIO/zigbee-adapter

package.json

I realized that I should use 0.3.1 rather than 0.3.0
since this code wasn't included in the 0.3.0 release.

Bumped version to 0.3.1

---

package.json
zb-adapter.js

When unable to find a Zigbee dongle, report the serial
ports that were found (makes debugging easier).

Add support for UARTSBee

---

package.json
zb-classifier.js
zb-node.js

This was introduced in the last release when support
for sensors was added.

Fix bug in classifying color lights

---

zb-adapter.js

When devices (like lights) rejoin the network, perhaps because they've
been physically turned off, their 16-bit address may change. Update
it and re-save the device info of this happens. This was a regression
introduced when adding persistence.

Update 16-bit address

---

zb-adapter.js
zb-at.js

The Digi dongles are supposed to come from the factory
with AP mode set to 1, but some come with AP mode set
to 2. Mode 2 caused character escaping to occur which
messes things up when you're not expecting it.

Set the API Mode if it isn't set properly

---

package.json
zb-adapter.js
zb-classifier.js

This fixes an issue where the smarthings sensors
appear to go non-responsive after removing and
re-adding them.

Requery the cieAddr when classifying the device

---

zb-xiaomi.js

Didn't have the actual device to try this out, but it seems  like a typo to me.

Fix typo in the name of lumi.sensor_magnet

---

zb-property.js

The Color class epxetcs Hue in the range 0-360 and Saturation 0-100.
Zigbee uses 0-254 for both of these.
The code which sets the color:
https://github.com/mozilla-iot/zigbee-adapter/blob/c3a9f90e746e35f6c8c5ef30c111bc53859bf9a2/zb-property.js#L723
does the correct scaling.
This PR fixes the parsing code which takes the zigbee values and converts
them back into RGB colors to apply the correct inverse scaling.

Fix calculation for Hue/Saturation

---

zb-adapter.js

This caused delays when adding iasZone sensors
(water leak, motion sensor, etc). Things would eventually
recover when the sensor sent in some data, but it might
take a couple minutes for this to occur.

Fix typo in zoneType logic

---

zb-adapter.js

The IEEE Address request requires a 16-bit address for
the frame itself since the message might be broadcast.
This looks like a regression introduced with the
multiple adapter support refactoring.

Fix IEEE Address Request Frame

---

package.json
yarn.lock
zb-adapter.js

Updated the yarn.lock to reference our modified versions
of zcl-id and zcl-packet.
Also made sure that all of the versions were in sync so
that zcl-id, zcl-pazcket, and zigbee-zdo all have empty
node_modules directories.

Update zcl id packet

---

deconz-driver.js
zb-driver.js

With the Conbee the watchdog triggering was largely
invisible since there was a usb-to-serial converter attached
to the AVR, and the AVR reset would only be noticed if there
were commands being processed at the time.
With the ConBee II, the MCU is directly connected to USB, so
when the MCU resets, it would dsiconnect from USB and would
need to be re-enumerated before comms would work.
Kicking the watchdog prevents the dongle from resetting.

Added support for the ConBee watchdog timer

---

zb-adapter.js

It turns out that the done callback isn't actually used
in the adapter, so this change won't affect anything but
it's good to get rid of the typo.

Fixes #112 - typo in zb-adapter.js (enumerateDoneCb)

---

zb-adapter.js

Hi,
I was trying to add some Nyce Open/Close sensors I have. But, they were not working. So, digging arround I discovered that the Match Descriptor Response was sending an invalid NWKAddrOfInterest address forcing the sensor to leave the network.
The NWKAddrOfInterest of the response must be the same of the request. The device is asking if the coordinator has the cluster. We need to answer that the coordinator has it, not the device.
At Zigbee specification, page 165, you can find this reference:
"If the NWKAddrOfInterest field of the original Match_Desc_req was not equal to
the broadcast network address for all devices for which macRxOnWhenIdle =
TRUE (0xfffd), the remote device shall set the NWKAddrOfInterest field to the
same network address that was specified in the original …

Fix Match_Desc_rsp with the correct NWKAddrOfInterest

---

zb-constants.js
zb-property.js
zb-xiaomi.js

I've added the cube controller for two different models "lumi.sensor_cube" and "lumi.sensor_cube.aqgl01" (https://www.aqara.com/us/cube.html, https://zigbee.blakadder.com/Xiaomi_MFKZQ01LM.html).
The cube provides two different properties:
* a state value, which converts the detected movement to one of the following states:
flip90, flip180, slide, tap, shake, wakeup
* the number of degrees, when the cube is rotated (the range is -180° to 180°)
It doesn't seem to be possible to parse the same zigbee property value more than once. It would probably be nicer if the different states would be boolean on/off values. However, the text values of the listed states can be used in the rules to trigger actions.

Added support for Xiaomi/Aqara Magic Cube

---

zb-classifier.js

https://github.com/mozilla-iot/gateway/issues/2571
I also noticed that properties have 'label' attributes. Shouldn't those be 'title' now? Or is that only for things?

make percentage multiple of 0.1

---

zb-classifier.js

an inline comment on this change is too long. I left it that way as I am uncertain of the preferred way to comment this kind of work-around. Please feel free to edit the PR or suggest how I should change the comment.
As far as I can tell, the latest remote from IKEA is either abusing the spec or, more likely, has a bug where '0005' ( = GENSCENES ) is missing from the output clusters. As this is the first time I've looked into this area, I may well be missing something significant.

workaround to enable Scenes on TRADFRI 5 button remote

---

zb-classifier.js

Constant `firstGenOnOffOutputEndpoint` was used before it was declared.
fixes #241

Fix ReferenceError

---

manifest.json
zb-classifier.js
zb-node.js
zb-property.js

This property attribute/property is hidden behind a configuration flag
On battery powered devices, suppresses the occasional log message
2020-11-21 00:58:46.994 INFO   : zigbee-adapter: handleReadRsp: ##### No property found for frame ##### zb-286d97000101d27f-door-sensor remote64: 286d97000101d27f profileId: 0104 clusterId: 0001 sourceEndpoint: 01 cmdId: report payload: [{"attrId":33,"dataType":32,"attrData":200}]

experimentally add batteryPercentageRemaining

---

zb-classifier.js
zb-constants.js

This is a solution for Issue #282, LIDL Livarno Lux Lights - Color Temperature not working.
Fixes #282

Added ColorTemperature property for ZHA devices

---

manifest.json
src/zb-adapter.js
src/zb-classifier.js

Please review both the use case and the implementation
Use case: I want to see when each Zigbee device was last active so that I can see if it has become disconnected or non-responsive
Implementation questions:
- general approach
- hooked into the correct places?
- names of periods?

RFC - connection aging

---

package-lock.json
package.json
src/zigbee2mqtt/zigbee2mqtt-device.ts
src/zigbee2mqtt/zigbee2mqtt-property.ts

Try upgrading the gateway-addon dependency to the same version used in gateway 1.2-alpha.1, to see whether this helps fix https://github.com/WebThingsIO/gateway/issues/3126

Upgrade gateway-addon dependency to 1.2

---

src/zb-classifier.js
src/zb-node.js
src/zb-property.js

Fixes https://github.com/WebThingsIO/gateway/issues/3126 for the Zigbee adapter.
In previous versions of the gateway all properties had a `visible` member which was set to true by default. The Zigbee adapter currently assumes that all properties have a `visible` member and removes from Thing Descriptions if it doesn't evaluate to `true`. The latest version of the gateway never adds a `visible` member to property descriptions.
This tweak makes sure that properties are not removed by default, and instead only removed if a `visible` member is explicitly set to `false`.
Invisible properties should eventually be re-factored out altogether, see #334.

Stop all properties being removed by default
